name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:

  build_and_test:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Solution1/UnitTest.sln'

    permissions: write-all

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x


    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG
      
    - name: Test
      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --logger "trx;LogFileName=test-results.xml" || true
      
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.xml"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: Run tests and push results to Xray
      run: bash scripts/push_test_results.sh --results-file Solution1/UnitTestProject/TestResults/test-results.xml
          
